$(document).ready(function(){
    $('#header_banner_right img').click(function(){
        $('#header_banner').slideUp()
    })
    $('#slide_box ul li:nth-child(1)').click(function(){
        $('#slide_bg1').fadeIn()
        $('#slide_bg2').fadeOut()
        $('#slide_bg3').fadeOut()
        $('#slide_bg4').fadeOut()
        $('#slide_bg5').fadeOut()
        $('#slide_bg6').fadeOut()
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#slide_box ul li:nth-child(2)').click(function(){
        $('#slide_bg2').fadeIn()
        $('#slide_bg1').fadeOut()
        $('#slide_bg3').fadeOut()
        $('#slide_bg4').fadeOut()
        $('#slide_bg5').fadeOut()
        $('#slide_bg6').fadeOut()
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#slide_box ul li:nth-child(3)').click(function(){
        $('#slide_bg3').fadeIn()
        $('#slide_bg1').fadeOut()
        $('#slide_bg2').fadeOut()
        $('#slide_bg4').fadeOut()
        $('#slide_bg5').fadeOut()
        $('#slide_bg6').fadeOut()
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#slide_box ul li:nth-child(4)').click(function(){
        $('#slide_bg4').fadeIn()
        $('#slide_bg1').fadeOut()
        $('#slide_bg2').fadeOut()
        $('#slide_bg3').fadeOut()
        $('#slide_bg5').fadeOut()
        $('#slide_bg6').fadeOut()
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#slide_box ul li:nth-child(5)').click(function(){
        $('#slide_bg5').fadeIn()
        $('#slide_bg1').fadeOut()
        $('#slide_bg2').fadeOut()
        $('#slide_bg3').fadeOut()
        $('#slide_bg4').fadeOut()
        $('#slide_bg6').fadeOut()
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#slide_box ul li:nth-child(6)').click(function(){
        $('#slide_bg6').fadeIn()
        $('#slide_bg2').fadeOut()
        $('#slide_bg3').fadeOut()
        $('#slide_bg4').fadeOut()
        $('#slide_bg5').fadeOut()
        $('#slide_bg1').fadeOut()
        $('#slide_box ul li:nth-child(6)').css({'transform':'scale(1.2)','background-color':'#fff'})
        $('#slide_box ul li:nth-child(2)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(3)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(4)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(5)').css({'transform':'scale(1)','background-color':'transparent'})
        $('#slide_box ul li:nth-child(1)').css({'transform':'scale(1)','background-color':'transparent'})
    })
    $('#section3_rightbox ul li').click(function(){
        $(this).css({'background-color':'#fff'})
        $(this).siblings('li').css({'background-color':'transparent'})
    })
    $('#section3_rightbox ul li:nth-child(1)').click(function(){
        $('#section3_img1').fadeIn(1000)
        $('#section3_img2').fadeOut(1000)
    })
    $('#section3_rightbox ul li:nth-child(2)').click(function(){
        $('#section3_img2').fadeIn(1000)
        $('#section3_img1').fadeOut(1000)
    })
});